//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Library
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Link { get; set; }
        public Nullable<System.DateTime> DateDelete { get; set; }
        public string Content { get; set; }
    }
}
