//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class u1436679_VolEventsBaseEntities : DbContext
    {
        public u1436679_VolEventsBaseEntities()
            : base("name=u1436679_VolEventsBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Library> Library { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserCheckCodeRef> UserCheckCodeRef { get; set; }
        public virtual DbSet<UserMac> UserMac { get; set; }
        public virtual DbSet<VolEvent> VolEvent { get; set; }
        public virtual DbSet<VolEventToUserRef> VolEventToUserRef { get; set; }
        public virtual DbSet<VolImageToEventRef> VolImageToEventRef { get; set; }
        public virtual DbSet<VolImg> VolImg { get; set; }
        public virtual DbSet<VolOrganization> VolOrganization { get; set; }
        public virtual DbSet<VolOrgToUserRef> VolOrgToUserRef { get; set; }
    }
}
