//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCheckCodeRef
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CheckCode { get; set; }
        public Nullable<System.DateTime> TimeSend { get; set; }
        public Nullable<System.DateTime> TimeValid { get; set; }
    }
}
