//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Family { get; set; }
        public Nullable<int> City { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<int> ImageId { get; set; }
        public Nullable<System.DateTime> DateReg { get; set; }
        public Nullable<System.DateTime> DateDelete { get; set; }
        public string Guid { get; set; }
        public bool Verifyed { get; set; }
        public byte[] Image { get; set; }
    }
}
