//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMac
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string MacAddress { get; set; }
        public Nullable<System.DateTime> DateChange { get; set; }
    }
}
