//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VolOrgToUserRef
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> VolOrgId { get; set; }
        public Nullable<int> Role { get; set; }
        public Nullable<System.DateTime> DateConnect { get; set; }
        public Nullable<System.DateTime> DateDisconnect { get; set; }
        public Nullable<System.DateTime> DateDelete { get; set; }
    }
}
